const countries = [
  { name: "United States", dialing_code: "+1" },
  { name: "Canada", dialing_code: "+1" },
  { name: "United Kingdom", dialing_code: "+44" },
  { name: "Australia", dialing_code: "+61" },
  { name: "Germany", dialing_code: "+49" },
  { name: "France", dialing_code: "+33" },
  { name: "Japan", dialing_code: "+81" },
  { name: "China", dialing_code: "+86" },
  { name: "Brazil", dialing_code: "+55" },
  { name: "South Africa", dialing_code: "+27" },
  { name: "India", dialing_code: "+91" },
  { name: "Russia", dialing_code: "+7" },
  { name: "Italy", dialing_code: "+39" },
  { name: "Spain", dialing_code: "+34" },
  { name: "Mexico", dialing_code: "+52" },
  { name: "Argentina", dialing_code: "+54" },
  { name: "Egypt", dialing_code: "+20" },
  { name: "Turkey", dialing_code: "+90" },
  { name: "Saudi Arabia", dialing_code: "+966" },
  { name: "Thailand", dialing_code: "+66" },
  { name: "Vietnam", dialing_code: "+84" },
  { name: "South Korea", dialing_code: "+82" },
  { name: "New Zealand", dialing_code: "+64" },
  { name: "Netherlands", dialing_code: "+31" },
  { name: "Sweden", dialing_code: "+46" },
  { name: "Norway", dialing_code: "+47" },
  { name: "Denmark", dialing_code: "+45" },
  { name: "Finland", dialing_code: "+358" },
  { name: "Switzerland", dialing_code: "+41" },
  { name: "Belgium", dialing_code: "+32" },
  { name: "Austria", dialing_code: "+43" },
  { name: "Portugal", dialing_code: "+351" },
  { name: "Greece", dialing_code: "+30" },
  { name: "Poland", dialing_code: "+48" },
  { name: "Czech Republic", dialing_code: "+420" },
  { name: "Hungary", dialing_code: "+36" },
  { name: "Israel", dialing_code: "+972" },
  { name: "United Arab Emirates", dialing_code: "+971" },
  { name: "Pakistan", dialing_code: "+92" },
  { name: "Sri Lanka", dialing_code: "+94" },
  { name: "Bangladesh", dialing_code: "+880" },
  { name: "Nepal", dialing_code: "+977" },
  { name: "Myanmar", dialing_code: "+95" },
  { name: "Malaysia", dialing_code: "+60" },
  { name: "Singapore", dialing_code: "+65" },
  { name: "Philippines", dialing_code: "+63" },
  { name: "Indonesia", dialing_code: "+62" },
  { name: "Jordan", dialing_code: "+962" },
  { name: "Lebanon", dialing_code: "+961" },
  { name: "Iraq", dialing_code: "+964" },
  { name: "Kuwait", dialing_code: "+965" },
  { name: "Oman", dialing_code: "+968" },
  { name: "Qatar", dialing_code: "+974" },
  { name: "Bahrain", dialing_code: "+973" },
  { name: "Kazakhstan", dialing_code: "+7" },
  { name: "Uzbekistan", dialing_code: "+998" },
  { name: "Turkmenistan", dialing_code: "+993" },
  { name: "Kyrgyzstan", dialing_code: "+996" },
  { name: "Tajikistan", dialing_code: "+992" },
  { name: "Georgia", dialing_code: "+995" },
  { name: "Armenia", dialing_code: "+374" },
  { name: "Azerbaijan", dialing_code: "+994" },
  { name: "Mongolia", dialing_code: "+976" },
  { name: "Nepal", dialing_code: "+977" },
  { name: "Brunei", dialing_code: "+673" },
  { name: "Maldives", dialing_code: "+960" },
  { name: "Laos", dialing_code: "+856" },
  { name: "Cambodia", dialing_code: "+855" },
  { name: "Sri Lanka", dialing_code: "+94" },
  { name: "Solomon Islands", dialing_code: "+677" },
  { name: "Vanuatu", dialing_code: "+678" },
  { name: "Fiji", dialing_code: "+679" },
  { name: "Papua New Guinea", dialing_code: "+675" },
  { name: "Samoa", dialing_code: "+685" },
  { name: "Tonga", dialing_code: "+676" },
  { name: "Kiribati", dialing_code: "+686" },
  { name: "Tuvalu", dialing_code: "+688" },
  { name: "Nauru", dialing_code: "+674" },
  { name: "Palau", dialing_code: "+680" },
  { name: "Marshall Islands", dialing_code: "+692" },
  { name: "Micronesia", dialing_code: "+691" },
  { name: "Northern Mariana Islands", dialing_code: "+1-670" },
];

export { countries };
