const countriesCode = [
  { name: "India", dialing_code: "+91", img: "/india.png" },
  { name: "United States", dialing_code: "+1", img: "/india.png" },
  { name: "Canada", dialing_code: "+1", img: "/india.png" },
  { name: "United Kingdom", dialing_code: "+44", img: "/india.png" },
  { name: "Australia", dialing_code: "+61", img: "/india.png" },
  { name: "Germany", dialing_code: "+49", img: "/india.png" },
  { name: "France", dialing_code: "+33", img: "/india.png" },
  { name: "Japan", dialing_code: "+81", img: "/india.png" },
  { name: "China", dialing_code: "+86", img: "/india.png" },
  { name: "Brazil", dialing_code: "+55", img: "/india.png" },
  { name: "South Africa", dialing_code: "+27", img: "/india.png" },
  { name: "Russia", dialing_code: "+7", img: "/india.png" },
  { name: "Italy", dialing_code: "+39", img: "/india.png" },
  { name: "Spain", dialing_code: "+34", img: "/india.png" },
  { name: "Mexico", dialing_code: "+52", img: "/india.png" },
  { name: "Argentina", dialing_code: "+54", img: "/india.png" },
  { name: "Egypt", dialing_code: "+20", img: "/india.png" },
  { name: "Turkey", dialing_code: "+90", img: "/india.png" },
  { name: "Saudi Arabia", dialing_code: "+966", img: "/india.png" },
  { name: "Thailand", dialing_code: "+66", img: "/india.png" },
  { name: "Vietnam", dialing_code: "+84", img: "/india.png" },
  { name: "South Korea", dialing_code: "+82", img: "/india.png" },
  { name: "New Zealand", dialing_code: "+64", img: "/india.png" },
  { name: "Netherlands", dialing_code: "+31", img: "/india.png" },
  { name: "Sweden", dialing_code: "+46", img: "/india.png" },
  { name: "Norway", dialing_code: "+47", img: "/india.png" },
  { name: "Denmark", dialing_code: "+45", img: "/india.png" },
  { name: "Finland", dialing_code: "+358", img: "/india.png" },
  { name: "Switzerland", dialing_code: "+41", img: "/india.png" },
  { name: "Belgium", dialing_code: "+32", img: "/india.png" },
  { name: "Austria", dialing_code: "+43", img: "/india.png" },
  { name: "Portugal", dialing_code: "+351", img: "/india.png" },
  { name: "Greece", dialing_code: "+30", img: "/india.png" },
  { name: "Poland", dialing_code: "+48", img: "/india.png" },
  { name: "Czech Republic", dialing_code: "+420", img: "/india.png" },
  { name: "Hungary", dialing_code: "+36", img: "/india.png" },
  { name: "Israel", dialing_code: "+972", img: "/india.png" },
  { name: "United Arab Emirates", dialing_code: "+971", img: "/india.png" },
  { name: "Pakistan", dialing_code: "+92", img: "/india.png" },
  { name: "Sri Lanka", dialing_code: "+94", img: "/india.png" },
  { name: "Bangladesh", dialing_code: "+880", img: "/india.png" },
  { name: "Nepal", dialing_code: "+977", img: "/india.png" },
  { name: "Myanmar", dialing_code: "+95", img: "/india.png" },
  { name: "Malaysia", dialing_code: "+60", img: "/india.png" },
  { name: "Singapore", dialing_code: "+65", img: "/india.png" },
  { name: "Philippines", dialing_code: "+63", img: "/india.png" },
  { name: "Indonesia", dialing_code: "+62", img: "/india.png" },
  { name: "Jordan", dialing_code: "+962", img: "/india.png" },
  { name: "Lebanon", dialing_code: "+961", img: "/india.png" },
  { name: "Iraq", dialing_code: "+964", img: "/india.png" },
  { name: "Kuwait", dialing_code: "+965", img: "/india.png" },
  { name: "Oman", dialing_code: "+968", img: "/india.png" },
  { name: "Qatar", dialing_code: "+974", img: "/india.png" },
  { name: "Bahrain", dialing_code: "+973", img: "/india.png" },
  { name: "Kazakhstan", dialing_code: "+7", img: "/india.png" },
  { name: "Uzbekistan", dialing_code: "+998", img: "/india.png" },
  { name: "Turkmenistan", dialing_code: "+993", img: "/india.png" },
  { name: "Kyrgyzstan", dialing_code: "+996", img: "/india.png" },
  { name: "Tajikistan", dialing_code: "+992", img: "/india.png" },
  { name: "Georgia", dialing_code: "+995", img: "/india.png" },
  { name: "Armenia", dialing_code: "+374", img: "/india.png" },
  { name: "Azerbaijan", dialing_code: "+994", img: "/india.png" },
  { name: "Mongolia", dialing_code: "+976", img: "/india.png" },
  { name: "Nepal", dialing_code: "+977", img: "/india.png" },
  { name: "Brunei", dialing_code: "+673", img: "/india.png" },
  { name: "Maldives", dialing_code: "+960", img: "/india.png" },
  { name: "Laos", dialing_code: "+856", img: "/india.png" },
  { name: "Cambodia", dialing_code: "+855", img: "/india.png" },
  { name: "Sri Lanka", dialing_code: "+94", img: "/india.png" },
  { name: "Solomon Islands", dialing_code: "+677", img: "/india.png" },
  { name: "Vanuatu", dialing_code: "+678", img: "/india.png" },
  { name: "Fiji", dialing_code: "+679", img: "/india.png" },
  { name: "Papua New Guinea", dialing_code: "+675", img: "/india.png" },
  { name: "Samoa", dialing_code: "+685", img: "/india.png" },
  { name: "Tonga", dialing_code: "+676", img: "/india.png" },
  { name: "Kiribati", dialing_code: "+686", img: "/india.png" },
  { name: "Tuvalu", dialing_code: "+688", img: "/india.png" },
  { name: "Nauru", dialing_code: "+674", img: "/india.png" },
  { name: "Palau", dialing_code: "+680", img: "/india.png" },
  { name: "Marshall Islands", dialing_code: "+692", img: "/india.png" },
  { name: "Micronesia", dialing_code: "+691", img: "/india.png" },
  {
    name: "Northern Mariana Islands",
    dialing_code: "+1-670",
    img: "/india.png",
  },
];

export { countriesCode };
